---
title: "DASHBOARD SOBRE LA METEOROLOGIA EN CANARIAS"
author: "Juan Carlos García Estupiñán"
date: '2024'
output: 
    flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE, include=FALSE, message=FALSE}
source("code/meteorologia_analysis.R")
source("code/mapa_canarias.R")
source("code/summary_table.R")
library(flexdashboard)
library(plotly)
```


GRÁFICAS
=======================================================================

Column {data-width=800}
-----------------------------------------------------------------------

### **Mapa de las estaciones meteorológicas de Canarias para los datos el último mes ([fuente: SITCAN, Gobierno de Canarias](https://opendata.sitcan.es/dataset/sistema-de-observacion-meteorologica-de-canarias))**

```{r, echo = FALSE, message = FALSE, warning=FALSE, out.width = '100%'}
map
```



Column 
-----------------------------------------------------------------------

### **Gráfico para la precipitación por mes** 

```{r warning=FALSE, message=FALSE, echo=FALSE}
ggplotly(precipitaciones_plot, tooltip = "text") %>% 
  layout(showlegend = FALSE)
```


### **Gráfico para la temperatura promedio por mes**

```{r warning=FALSE, message=FALSE, echo=FALSE}
ggplotly(temperatura_plot, tooltip = "text") %>% 
  layout(showlegend = FALSE)
```


TABLAS
=======================================================================

```{r warning=FALSE, message=FALSE, echo=FALSE}
gt_table
```
